import { generateObject, embed } from 'ai';
import { z } from 'zod';
import { google, DEFAULT_MODEL_NAME } from './client';
import type { InsertAnalysisInput, SentimentLabel, BiasLabel, Json } from '../supabase/types';

export const articleAnalysisSchema = z.object({
  summary: z
    .string()
    .describe('A concise, neutral, 1-3 paragraph summary of the news article based solely on the article text.'),
  sentiment_score: z
    .number()
    .min(-1.0)
    .max(1.0)
    .describe('Sentiment score from -1.0 (very negative) to 1.0 (very positive).'),
  sentiment_label: z
    .enum(['positive', 'neutral', 'negative'])
    .describe('Categorical sentiment label.'),
  left_percentage: z
    .number()
    .min(0)
    .max(100)
    .describe('Estimated percentage of political framing from left-leaning perspectives (0 to 100).'),
  center_percentage: z
    .number()
    .min(0)
    .max(100)
    .describe('Estimated percentage of neutral/centrist framing (0 to 100).'),
  right_percentage: z
    .number()
    .min(0)
    .max(100)
    .describe('Estimated percentage of political framing from right-leaning perspectives (0 to 100).'),
  bias_label: z
    .enum(['left', 'center', 'right', 'mixed', 'unclear'])
    .describe('Primary political framing label based on evidence in the text.'),
  confidence: z
    .number()
    .min(0.0)
    .max(1.0)
    .describe('Confidence score in this framing analysis from 0.0 to 1.0.'),
  framing_notes: z
    .string()
    .describe('Detailed explanatory notes on tone, headline framing, word choices, and selective reporting in the text.'),
  loaded_terms: z
    .array(
      z.object({
        term: z.string().describe('Emotionally charged or politically loaded word or phrase found in the text.'),
        context: z.string().describe('Brief context or explanation of how the term was used.'),
      })
    )
    .describe('List of loaded terms or phrases present in the article.'),
  disclaimer: z
    .string()
    .default('AI-estimated analysis. Framing and sentiment are generated by AI models and do not represent absolute factual truth.')
    .describe('Disclaimer text for AI-generated media analysis.'),
});

export type ArticleAnalysisOutput = z.infer<typeof articleAnalysisSchema>;

const SYSTEM_PROMPT = `
You are an expert, non-partisan news analyst for Veritas News.
Your task is to analyze news articles objectively for sentiment, political framing, loaded vocabulary, and perspective.

CRITICAL RULES:
1. Base your analysis STRICTLY on the article text provided.
2. DO NOT infer political bias or framing from the publisher or source name. Evaluate ONLY the text content of the article itself.
3. Determine left_percentage, center_percentage, and right_percentage based on text framing, quote selection, topic focus, and vocabulary. The three percentages MUST sum to 100.
4. Set bias_label to:
   - 'left' if left_percentage is dominant and significantly higher than right_percentage
   - 'right' if right_percentage is dominant and significantly higher than left_percentage
   - 'center' if center_percentage is dominant or neutral balance is maintained
   - 'mixed' if both left and right elements are prominent
   - 'unclear' if text evidence is weak, incomplete, or ambiguous
5. Evaluate sentiment objectively (-1.0 to 1.0) and set sentiment_label accordingly ('positive', 'neutral', 'negative').
6. Provide clear, nuanced framing_notes explaining the tone, perspective, and key framing techniques observed.
7. Identify any loaded terms or emotionally charged language in loaded_terms.
`;

/**
 * Normalizes left, center, right percentages so they are non-negative integers summing to exactly 100.
 */
function normalizePercentages(rawLeft: number, rawCenter: number, rawRight: number): {
  left: number;
  center: number;
  right: number;
} {
  let left = Math.round(Math.max(0, rawLeft));
  let center = Math.round(Math.max(0, rawCenter));
  let right = Math.round(Math.max(0, rawRight));

  const sum = left + center + right;

  if (sum === 0) {
    return { left: 0, center: 100, right: 0 };
  }

  if (sum !== 100) {
    const diff = 100 - sum;
    if (center >= left && center >= right) {
      center += diff;
    } else if (left >= right) {
      left += diff;
    } else {
      right += diff;
    }
  }

  return {
    left: Math.max(0, Math.min(100, left)),
    center: Math.max(0, Math.min(100, center)),
    right: Math.max(0, Math.min(100, right)),
  };
}

/**
 * Generates vector embedding for article text using Gemini gemini-embedding-001 model.
 */
export async function generateArticleEmbedding(
  title: string,
  rawText: string
): Promise<number[]> {
  const textToEmbed = `${title}\n\n${rawText}`.slice(0, 8000);
  const { embedding } = await embed({
    model: google.textEmbeddingModel('gemini-embedding-001'),
    value: textToEmbed,
  });
  return embedding.slice(0, 768);
}

/**
 * Analyzes article text using Vercel AI SDK with Google Gemini model.
 * Performs output validation, framing percentage normalization, and bias score calculation.
 */
export async function analyzeArticle(
  articleId: string,
  title: string,
  rawText: string
): Promise<InsertAnalysisInput> {
  let attempts = 0;
  const maxAttempts = 2;
  let lastError: Error | null = null;

  const promptText = `Article Title: ${title}\n\nArticle Body:\n${rawText}`;

  while (attempts < maxAttempts) {
    attempts++;
    try {
      const result = await generateObject({
        model: google(DEFAULT_MODEL_NAME),
        schema: articleAnalysisSchema,
        system: SYSTEM_PROMPT,
        prompt: promptText,
      });

      const data = result.object;

      // Normalize framing percentages to ensure exact 100% sum
      const normalizedFraming = normalizePercentages(
        data.left_percentage,
        data.center_percentage,
        data.right_percentage
      );

      // Compute derived bias_score: (right_percentage - left_percentage) / 100
      const bias_score = Number(
        ((normalizedFraming.right - normalizedFraming.left) / 100).toFixed(4)
      );

      const insertInput: InsertAnalysisInput = {
        article_id: articleId,
        summary: data.summary,
        sentiment_score: Number(data.sentiment_score.toFixed(4)),
        sentiment_label: data.sentiment_label as SentimentLabel,
        bias_score: bias_score,
        bias_label: data.bias_label as BiasLabel,
        left_percentage: normalizedFraming.left,
        center_percentage: normalizedFraming.center,
        right_percentage: normalizedFraming.right,
        confidence: Number(data.confidence.toFixed(4)),
        framing_notes: data.framing_notes,
        loaded_terms: data.loaded_terms as unknown as Json,
        disclaimer:
          data.disclaimer ||
          'AI-estimated analysis. Framing and sentiment are generated by AI models and do not represent absolute factual truth.',
        model: DEFAULT_MODEL_NAME,
      };

      return insertInput;
    } catch (err) {
      lastError = err instanceof Error ? err : new Error(String(err));
      console.warn(
        `AI Analysis attempt ${attempts}/${maxAttempts} failed for article ${articleId}: ${lastError.message}`
      );
    }
  }

  throw new Error(
    `Failed to generate valid AI analysis for article ${articleId} after ${maxAttempts} attempts: ${lastError?.message}`
  );
}
